version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  pack:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm pack
            - run: mkdir /home/circleci/project/dist
            - run: mv *.tgz /home/circleci/project/dist
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - pack:
            requires:
              - build-and-test