version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
         name: Install Dependencies
         command: |
           npm install
      - run:
         name: Run Tests
         command: |
           npm test
  pack:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
         name: Install Dependencies
         command: |
           npm install
      - run:
         name: compiles
         command: |
           npm pack .
           mkdir /home/circleci/project/dist
           mv *.tgz /home/circleci/project/dist
      - store_artifacts:
         path: dist

workflows:
  build-and-package:
    jobs:
      - build-and-test
      - pack:
          requires:
            - build-and-test
